# .travis.yml
#
# YAML configuration file for the continuous integration platform "Travis CI".
#
#          Copyright Florian Wolters 2014.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  # Install and build Google Test.
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make
  - sudo mv libgtest* /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

install:
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - clang++ --version
  - gcc --version
  - ld --version
  - cmake --version
  - make --version
  - make

notifications:
  email:
    on_success: change
    on_failure: always
