# .travis.yml
#
# YAML configuration file for the continuous integration platform "Travis CI".
#
# Copyright Florian Wolters 2014 (http://blog.florianwolters.de).
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

language: cpp

compiler:
  - clang
  - gcc

before_install:
  # Add Advanced Packaging Tool (APT) repository for Ubuntu.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # Add APT repository for CMake.
  - sudo add-apt-repository -y ppa:kalakris/cmake

  # Add APT repository for Clang.
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'; fi
  # Retrieve the archive signature for Clang.
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

  # Re-synchronize the package index files from their sources.
  - sudo apt-get update -qq

install:
  # Install CMake.
  - sudo apt-get install -qq cmake

  # Install GNU Standard C++ Library. 
  - sudo apt-get install libstdc++-4.9-dev

  # Install GCC.
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; export CXX="g++-4.9" CC="gcc-4.9"; fi

  # Install Clang.
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install clang-3.5; export CXX="clang++-3.5" CC="clang"; fi

  # Install Google Test.
  - sudo apt-get install libgtest-dev

  # Build Google Test.
  - cd /usr/src/gtest
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make
  - sudo mv libgtest* /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - mkdir build
  - cd build

  # Run CMake.
  - cmake ..

script:
  - cmake --version
  - $CXX --version
  - make --version

  # Run GNU Make.
  - make

  # Run CTest.
  - ctest -V

notifications:
  email:
    on_success: change
    on_failure: always
